name: Signeur
options:
  minimumXcodeGenVersion: 2.38.0
packages:
  SigneurCore:
    path: .
settings:
  base:
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1
targets:
  Signeur:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - iOSApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.trustroots.signeur
        PRODUCT_NAME: Signeur
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: iOSApp/Info.plist
        SWIFT_VERSION: 5.10
        CODE_SIGN_STYLE: Automatic
      configs:
        Debug:
          DEVELOPMENT_TEAM: SUJ594N47C
    dependencies:
      - package: SigneurCore
        product: SigneurCore
  SigneurMac:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - MacOSApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.trustroots.signeur.mac
        PRODUCT_NAME: Signeur
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: MacOSApp/SigneurMac.entitlements
        INFOPLIST_FILE: MacOSApp/Info.plist
        SWIFT_VERSION: 5.10
        CODE_SIGN_STYLE: Automatic
      configs:
        Debug:
          DEVELOPMENT_TEAM: SUJ594N47C
        Release:
          ENABLE_HARDENED_RUNTIME: YES
    dependencies:
      - package: SigneurCore
        product: SigneurCore
  SigneurE2ETests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - E2ETests/iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.trustroots.signeur.e2e-tests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.10
        TEST_TARGET_NAME: Signeur
    dependencies:
      - target: Signeur
  SigneurMacE2ETests:
    type: bundle.ui-testing
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - E2ETests/macOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.trustroots.signeur.mac.e2e-tests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.10
        TEST_TARGET_NAME: SigneurMac
    dependencies:
      - target: SigneurMac
schemes:
  Signeur:
    build:
      targets:
        Signeur: all
        SigneurE2ETests: [test]
    test:
      targets:
        - SigneurE2ETests
  SigneurMac:
    build:
      targets:
        SigneurMac: all
        SigneurMacE2ETests: [test]
    test:
      targets:
        - SigneurMacE2ETests
