name: Signstr
options:
  minimumXcodeGenVersion: 2.38.0
packages:
  SignstrCore:
    path: .
settings:
  base:
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1
targets:
  Signstr:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - iOSApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.trustroots.signstr
        PRODUCT_NAME: Signstr
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: iOSApp/Info.plist
        SWIFT_VERSION: 5.10
        CODE_SIGN_STYLE: Automatic
      configs:
        Debug:
          DEVELOPMENT_TEAM: SUJ594N47C
    dependencies:
      - package: SignstrCore
        product: SignstrCore
  SignstrMac:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - MacOSApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.trustroots.signstr.mac
        PRODUCT_NAME: Signstr
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: MacOSApp/SignstrMac.entitlements
        INFOPLIST_FILE: MacOSApp/Info.plist
        SWIFT_VERSION: 5.10
        CODE_SIGN_STYLE: Automatic
      configs:
        Debug:
          DEVELOPMENT_TEAM: SUJ594N47C
        Release:
          ENABLE_HARDENED_RUNTIME: YES
    dependencies:
      - package: SignstrCore
        product: SignstrCore
scheme:
  testTargets: []
